/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeiticosRouteImport } from './routes/feiticos'
import { Route as OrChar225culoseconsultasRouteImport } from './routes/oráculos e consultas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeiticosRoute = FeiticosRouteImport.update({
  id: '/feiticos',
  path: '/feiticos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrChar225culoseconsultasRoute =
  OrChar225culoseconsultasRouteImport.update({
    id: '/oráculos e consultas',
    path: '/oráculos e consultas',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feiticos': typeof FeiticosRoute
  '/oráculos e consultas': typeof OrChar225culoseconsultasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feiticos': typeof FeiticosRoute
  '/oráculos e consultas': typeof OrChar225culoseconsultasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feiticos': typeof FeiticosRoute
  '/oráculos e consultas': typeof OrChar225culoseconsultasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/feiticos' | '/oráculos e consultas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/feiticos' | '/oráculos e consultas'
  id: '__root__' | '/' | '/feiticos' | '/oráculos e consultas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeiticosRoute: typeof FeiticosRoute
  OrChar225culoseconsultasRoute: typeof OrChar225culoseconsultasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feiticos': {
      id: '/feiticos'
      path: '/feiticos'
      fullPath: '/feiticos'
      preLoaderRoute: typeof FeiticosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oráculos e consultas': {
      id: '/oráculos e consultas'
      path: '/oráculos e consultas'
      fullPath: '/oráculos e consultas'
      preLoaderRoute: typeof OrChar225culoseconsultasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeiticosRoute: FeiticosRoute,
  OrChar225culoseconsultasRoute: OrChar225culoseconsultasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
